//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoServiceProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TechnoDatabaseEntities : DbContext
    {
        private static TechnoDatabaseEntities technoDatabaseEntities;
        public TechnoDatabaseEntities()
            : base("name=TechnoDatabaseEntities")
        {
        }
        public static TechnoDatabaseEntities GetTechnoDatabase()
        {
            if (technoDatabaseEntities == null)
            {
                technoDatabaseEntities = new TechnoDatabaseEntities();
            }
            return technoDatabaseEntities;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Заявки> Заявки { get; set; }
        public virtual DbSet<Неисправности> Неисправности { get; set; }
        public virtual DbSet<Оборудование> Оборудование { get; set; }
        public virtual DbSet<Пользователь> Пользователь { get; set; }
        public virtual DbSet<Роли> Роли { get; set; }
        public virtual DbSet<Статус> Статус { get; set; }
    }
}
