//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoServiceProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявки
    {
        public int Код { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public int Код_клиента { get; set; }
        public Nullable<int> Код_исполнителя { get; set; }
        public int Код_оборудования { get; set; }
        public int Код_неисправности { get; set; }
        public int Код_статуса { get; set; }
        public string Коммент_исполнителя { get; set; }
        public Nullable<int> Дни_выполнения { get; set; }
    
        public virtual Неисправности Неисправности { get; set; }
        public virtual Оборудование Оборудование { get; set; }
        public virtual Пользователь Пользователь { get; set; }
        public virtual Пользователь Пользователь1 { get; set; }
        public virtual Статус Статус { get; set; }
    }
}
